mybatis:
  type-aliases-package: com.dj.springboot.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
 helperDialect: mysql
 reasonable: false # 如果没有数据  返回空 而非最后一页的数据
 supportMethodsArguments: true
 params: count=countSql
 returnPageInfo: check

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lk?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/page/

  thymeleaf:
    prefix: classpath:/templates/

logging:
  level:
    com.dj.springboot.springboot.mapper: debug
